Issue/#30
StelFoog/speakeasy pull request #37
Opened 2021-12-14 10:54 UTC by HannesSundin

refactored login page and the used components.
some views moved to temp/folder, to be used in staff registration
and some views moved into index.js

2021-12-14 14:10 UTC, StelFoog requested changes

2021-12-14 14:10 UTC, StelFoog commented on pages/index.js
>  			<main className={styles.main}>
Everything in main should be it's own non-reusable component (in this same file) to match the MVP-pattern, e.g.
```js
function LoginForm({pnr, setPnr, password, setPassword, handleSubmit}) {
  return (
    <form
      onSubmit={e => {
        e.preventDefault();
        handleSubmit();
      }}
    >
      {/* TODO */}
    </form>
}


export default Index() {
  const [pnr, setPnr] = useState("");
  const [password, setPassword] = useSate("");
  
  function handleSubmit() {
    /* todo */
  }

  return (
    <>
      <Head>{/*...*/}</Head>
      <main>
        <LoginForm pnr={pnr} setPnr={setPnr} password={password} setPassword={setPassword} handleSubmit={handleSubmit}  />
        {/* Other things */}
      </main>
    </>
  )
}
```

2021-12-14 14:10 UTC, StelFoog commented on components/ErrorTextView.js
> +}
It's a component and should be named as such, file should probably be called `ErrorText.js`

2021-12-14 14:10 UTC, StelFoog commented on components/RequiredTextView.js
> +}
It's a component and should be named as such, file should probably be called `ErrorText.js`

2021-12-14 14:10 UTC, StelFoog commented on components/RequiredTextView.js
> +}
missing EOF

2021-12-14 15:10 UTC, HannesSundin commented on pages/index.js
> +					<button
commit e65371554d00de7a0aea883321e5c7829446b76a

2021-12-14 15:10 UTC, HannesSundin commented on pages/index.js
> +						onClick={() => {
commit e65371554d00de7a0aea883321e5c7829446b76a

2021-12-14 15:10 UTC, HannesSundin commented on pages/index.js
>  			<main className={styles.main}>
commit e65371554d00de7a0aea883321e5c7829446b76a

2021-12-14 15:10 UTC, HannesSundin commented on components/ErrorTextView.js
> +}
commit e65371554d00de7a0aea883321e5c7829446b76a

2021-12-14 15:10 UTC, HannesSundin commented on components/RequiredTextView.js
> +}
commit e65371554d00de7a0aea883321e5c7829446b76a

2021-12-14 15:10 UTC, HannesSundin commented on components/RequiredTextView.js
> +}
commit e65371554d00de7a0aea883321e5c7829446b76a

2021-12-14 16:40 UTC, HannesSundin commented on pages/index.js
> +        fetch('/api/staff/login', {
do you mean to check if PIN contains numbers?
pressing enter while the button is disabled does nothing for me.

2021-12-15 11:04 UTC, StelFoog commented on pages/index.js
> +        fetch('/api/staff/login', {
strange seems to have fixed itself

2021-12-15 11:52 UTC, merged